env:
  # Telegram
  TG_CHAT: -1001885973208
  TG_TOKEN: ENCRYPTED[b7b2ef1d06fabce335912a41d34c24c39d2183b91226270b4acb8c397af252f522d1c4255f31dbce2c0f5308657b456f]

task:
  name: "KERNEL BUILD CI by RullV2"
  skip: $CIRRUS_BRANCH == 'master'

  timeout_in: 120m
  container:
      image: ubuntu
      privileged: true
      cpu: 8
      memory: 10G
      
  setup_script:
      - apt update
      - apt upgrade -y
      - apt install wget git -y
      - wget https://raw.githubusercontent.com/TheUnknownName/toolFW/main/setup.sh
      - bash setup.sh

  build_script:
      - wget https://raw.githubusercontent.com/cumaRull/Kernel-Builder-CI/master/build.sh
      - chmod +x build.sh
      - ./build.sh ${CIRRUS_WORKING_DIR}/name-kernel.txt
